version: "3.5"

services:
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        networks:
            - falc-local

networks:
    falc-local:
        driver: bridge